### ISSUE TITLE
[FEAT] Add Components for Patron/Enforcement Profiles

### ISSUE THREAD

**Issue by Nasiff** [Nasiff/School-Attendance-System#17]
Designs:
https://media.discordapp.net/attachments/780532498428985364/780957610957340672/unknown.png?width=469&height=565
https://media.discordapp.net/attachments/780532498428985364/780957823520997376/unknown.png?width=557&height=564

**Comment by czarhassan** [comment]
https://cdn.discordapp.com/attachments/780532498428985364/780966450138447922/unknown.png

**Comment by czarhassan** [comment]
User Profile page of enforcement officer
![image](https://user-images.githubusercontent.com/46304552/100170086-e494ec00-2e92-11eb-9053-adb5d92178e4.png)

**Comment by czarhassan** [comment]
User Profile page for patron
![image](https://user-images.githubusercontent.com/46304552/100170284-481f1980-2e93-11eb-8018-7ef41070fb18.png)

**Comment by Nasiff** [comment]
Taken care of by PR #21
