### ISSUE TITLE
Enforcer Designs

### ISSUE THREAD

**Issue by rgzahedi** [Nasiff/School-Attendance-System#18]
When the Enforcement clicks on "Issue a Ticket", it should send them to this screen:
![image](https://user-images.githubusercontent.com/19274017/100182577-f2ef0200-2eaa-11eb-9143-ca308ae6ebd5.png)

When the Enforcement clicks on "User Profile" from the user button on the top right on the page:
![image](https://user-images.githubusercontent.com/19274017/100182695-3d707e80-2eab-11eb-9004-af05627ebe07.png)

When the Enforcement clicks on "Review Incident Reports" from the user profile page
![image](https://user-images.githubusercontent.com/19274017/100182556-e9fe3080-2eaa-11eb-8af4-1936b1c6b1bb.png)

**Comment by rgzahedi** [comment]
Pending: Waiting for more designs for enforcer

**Comment by rgzahedi** [comment]
So the two images below, the first one is an image of the issue given to the enforcer from the patron and all the information shown has already been given by the patron, so the only thing that the enforcer needs to do is to check if valid or invalid, also if the patron requests a refund, there will be a box where it says "Patron requests refund!" in red, so the officer knows, otherwise don't include it. When the officer hits valid, it should show that the box has been clicked on (e.g. highlighted), if the patron requests a refund and the officer hits valid, there should be a pop-up window where the second image shows where the officer confirms or denies refund by either clicking yes or no and showing a highlight to prove that it has been clicked on. Then you click submit on the pop up and the pop up closes, then you submit the entire report at the bottom. If you click invalid on the report, you must give reason on a textbox and then you submit from there. 
![image](https://user-images.githubusercontent.com/19274017/100298901-4bcca200-2f60-11eb-970a-59d14c067c2a.png)
![image](https://user-images.githubusercontent.com/19274017/100298880-3a839580-2f60-11eb-8c5e-63e661f6c564.png)

**Comment by czarhassan** [comment]
Enforcement Officer's login page
![image](https://user-images.githubusercontent.com/46304552/100302837-2a23e880-2f69-11eb-82fc-b4cb702e1b36.png)

**Comment by czarhassan** [comment]
Registration page for Enforcement officer
![image](https://user-images.githubusercontent.com/46304552/100302899-49bb1100-2f69-11eb-8840-98c161291fd6.png)

**Comment by czarhassan** [comment]
Enforcement officer's profile page where they can edit
![image](https://user-images.githubusercontent.com/46304552/100303008-8dae1600-2f69-11eb-8d6c-01b09481357d.png)

**Comment by czarhassan** [comment]
Enforcement Officer's result page when they search for a parking location and they have the ability to edit any one of them
![image](https://user-images.githubusercontent.com/46304552/100303099-c352ff00-2f69-11eb-9b10-a0d7d8b18de9.png)

**Comment by czarhassan** [comment]
When the officer selects a parking location to edit, they are present with this page where they can change these attributes
![image](https://user-images.githubusercontent.com/46304552/100303200-fd240580-2f69-11eb-9da4-7c98785d7793.png)

**Comment by Nasiff** [comment]
Done
