### ISSUE TITLE
Patron Designs

### ISSUE THREAD

**Issue by rgzahedi** [Nasiff/School-Attendance-System#19]
@czarhassan please add in all patron designs in this issue, whatever you have

**Comment by czarhassan** [comment]
Patron Registration Page
![image](https://user-images.githubusercontent.com/46304552/100301677-a832c000-2f66-11eb-958c-9ac990f10d40.png)

**Comment by czarhassan** [comment]
Patron is shown a list of all parking spots within a 25KM radius. Patron selects the Parking Location they want and click confirm to go to the next page
![image](https://user-images.githubusercontent.com/46304552/100301807-fb0c7780-2f66-11eb-869c-feca13335830.png)

**Comment by czarhassan** [comment]
Patron after selecting a parking location is shown more information where they can select the parking spot, the date and time, and for how long they want to reserve the spot (maximum of 3 hours)
![image](https://user-images.githubusercontent.com/46304552/100301961-4cb50200-2f67-11eb-906f-2756c80c5360.png)

**Comment by czarhassan** [comment]
Patron's Report an Issue page where they can fill out a report and request for a refund. If the user selects "Parking Law Violation," form 1 is displayed, and form 2 is displayed if they selected "Inaccessible Parking Spot."
![image](https://user-images.githubusercontent.com/46304552/100302171-bdf4b500-2f67-11eb-8a5f-e5c3d4003e2d.png)

**Comment by czarhassan** [comment]
Patron's Login Page
![image](https://user-images.githubusercontent.com/46304552/100302414-44a99200-2f68-11eb-8f73-fcc3b33a62ce.png)

**Comment by czarhassan** [comment]
Patron's page for editing their profile
![image](https://user-images.githubusercontent.com/46304552/100302722-ecbf5b00-2f68-11eb-83d7-2aa82f14cd4f.png)

**Comment by Nasiff** [comment]
Done
